name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # - name: Create CloudFormation stack
      #   run: |
      #     aws cloudformation create-stack --stack-name osamadeploy --template-body --template-file workshop4.yaml --region us-east-1 --capabilities CAPABILITY_NAMED_IAM

      # - name: Wait for Stack to Complete
      #   run: |
      #     aws cloudformation wait stack-create-complete --stack-name osamadeploy --region us-east-1 --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy --stack-name osamadeploy --template-file workshop4.yaml  --region us-east-1 --capabilities CAPABILITY_NAMED_IAM
