name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          export AWS_ACCESS_KEY_ID=AKIARZF4REMN42VXOYJC
          export AWS_SECRET_ACCESS_KEY=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
          export AWS_REGION=us-east-1
          
        # uses: aws-actions/configure-aws-credentials@v1
        # with:
        #   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   aws-region: us-east-1
        # run: |
        #   echo "[default] aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }} aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials


      # - name: Create CloudFormation stack
      #   run: |
      #     aws cloudformation create-stack --stack-name osamadeploy --template-body --template-file workshop4.yaml --region us-east-1 --capabilities CAPABILITY_NAMED_IAM

      # - name: Wait for Stack to Complete
      #   run: |
      #     aws cloudformation wait stack-create-complete --stack-name osamadeploy --region us-east-1 --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy --stack-name osamadeploy --template-file workshop4.yaml  --region us-east-1 --capabilities CAPABILITY_NAMED_IAM
